services:
  manager:
    image: media-router
    pull_policy: never
    restart: unless-stopped
    build: .
    ports:
      - "8080:8080"   # WebApp
      - "3000:3000"   # router configuration
    working_dir: /app/server/scripts
    volumes:
      - ./server/profileConf.json/:/app/server/profileConf.json
      - ./server/managerConf.json/:/app/server/managerConf.json
    command: node ../manager
  router:
    image: media-router
    pull_policy: never
    restart: unless-stopped
    ports:
      - "8890:8890"   # SRT
      - "9090:9090"   # New WebRCT
      - "2000:2000"   # WebApp for WebRTC
      - "8081:8081"   # WebApp for Control
      - "8082:8082"   # WebApp for Profile Manager
    environment:
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    volumes:
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
      - ./server/profileConf.json/:/app/server/profileConf.json
      - ./server/managerConf.json/:/app/server/managerConf.json
    working_dir: /app/server/scripts
    devices:
      - /dev/snd
    group_add:
      - audio
    command: node ../router
  mediamtx:
    image: bluenviron/mediamtx
    restart: unless-stopped
    ports:
      - "8889:8889/tcp"   # WebRTC
      - "8189:8189/udp"   # ICE/UDP
    volumes:
      - ./example/AudioSRT_to_WebRTC/mediamtx.yml:/mediamtx.yml:ro